services:
  postgres:
    image: postgres:17.0
    restart: always
    network_mode: host
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/data/db

  redis:
    image: redis:7.4.2
    restart: always
    network_mode: host
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
    external: true
  redis_data:
    external: true
